#!/bin/busybox sh
#TODO: need to be cleaned after systemd bug fix.
mount -o rw,relatime,thread_pool=4,space_cache,subvol=@home /dev/mapper/linuxdata $NEWROOT_MNT/home
mount -o rw,relatime,thread_pool=4,space_cache,subvol=@cdimage /dev/mapper/linuxdata $NEWROOT_MNT/mnt/cdimage
mount -o rw,relatime,thread_pool=4,space_cache,subvol=@qemudisk /dev/mapper/linuxdata $NEWROOT_MNT/mnt/qemudisk
